#!/usr/bin/perl

# Created on: 2010-01-04 22:09:35
# Create by:  Ivan Wills
# $Id$
# $Revision$, $HeadURL$, $Date$
# $Revision$, $Source$, $Date$

use strict;
use warnings;
use version;
use List::Util qw/sum/;
use Getopt::Long;
use Pod::Usage;
use Data::Dumper qw/Dumper/;
use English qw/ -no_match_vars /;
use FindBin qw/$Bin/;
use Game::Life::Adv qw/game_of_life/;

our $VERSION = version->new('0.0.1');
my ($name)   = $PROGRAM_NAME =~ m{^.*/(.*?)$}mxs;

my %option = (
    max     => 10,
    live    => 5,
    die     => 1,
    verbose => 0,
    man     => 0,
    help    => 0,
    VERSION => 0,
);

if ( !@ARGV ) {
    pod2usage( -verbose => 1 );
}

main();
exit 0;

sub main {

    Getopt::Long::Configure('bundling');
    GetOptions(
        \%option,
        'live|l=i',
        'die|d=i',
        'max|m=i',
        'wrap|w',
        'verbose|v+',
        'man',
        'help',
        'VERSION!',
    ) or pod2usage(2);

    if ( $option{'VERSION'} ) {
        print "$name Version = $VERSION\n";
        exit 1;
    }
    elsif ( $option{'man'} ) {
        pod2usage( -verbose => 2 );
    }
    elsif ( $option{'help'} ) {
        pod2usage( -verbose => 1 );
    }

    # do stuff here
    my $dim = [ map { $_ - 1 } @ARGV ];
    my $gof = Game::Life::Adv::game_of_life(
        dims => $dim,
        rand => 1,
        wrap => $option{wrap},
    );
    my $count = 0;

    $gof->add_rule(
        sub {
            my $sub = sum $_[0]->surround;
            if ("$_[0]" eq '1') {
                return
                      $sub == 0 ? undef
                    : $sub == 1 ? undef
                    : $sub == 2 ? undef
                    : $sub == 3 ? undef
                    : $sub == 4 ? undef
                    : $sub == 5 ? undef
                    : $sub == 6 ? 0
                    : $sub == 7 ? 0
                    : $sub == 8 ? 0
                    : $sub == 9 ? 0
                    :             undef;
            }
            else {
                return
                      $sub == 0 ? undef
                    : $sub == 1 ? undef
                    : $sub == 2 ? undef
                    : $sub == 3 ? 1
                    : $sub == 4 ? 1
                    : $sub == 5 ? 1
                    : $sub == 6 ? 1
                    : $sub == 7 ? 1
                    : $sub == 8 ? 1
                    : $sub == 9 ? 1
                    :             undef;
            }
        },
        #live => 5,
        #die  => 1,
    );

    my $last = "$gof\n";
    print $last;
    sleep 1;

    while ( $count++ < $option{max} && $gof->process ) {
        $gof->set;
        my $cur = "$gof\n";
        die "Static game\n" if $cur eq $last;
        print $cur;
        $last = $cur;
#		die Dumper $gof->board->items;
        sleep 1;
    }

    return;
}

__DATA__

=head1 NAME

simple - Simple game of life usage

=head1 VERSION

This documentation refers to simple version 0.1.

=head1 SYNOPSIS

   simple [option]

 OPTIONS:
  -l --live[=]int   Number of surrouding lifes to continue living
  -d --die[=]int    This number or more surrounding lifes causes death
  -m --max[=]int    Max
  -w --wrap         Wrap the board

  -v --verbose      Show more detailed option
     --version      Prints the version information
     --help         Prints this help information
     --man          Prints the full documentation for simple

=head1 DESCRIPTION

A full description of the module and its features.

May include numerous subsections (i.e., =head2, =head3, etc.).


=head1 SUBROUTINES/METHODS

A separate section listing the public components of the module's interface.

These normally consist of either subroutines that may be exported, or methods
that may be called on objects belonging to the classes that the module
provides.

Name the section accordingly.

In an object-oriented module, this section should begin with a sentence (of the
form "An object of this class represents ...") to give the reader a high-level
context to help them understand the methods that are subsequently described.

=head1 DIAGNOSTICS

A list of every error and warning message that the module can generate (even
the ones that will "never happen"), with a full explanation of each problem,
one or more likely causes, and any suggested remedies.

=head1 CONFIGURATION AND ENVIRONMENT

A full explanation of any configuration system(s) used by the module, including
the names and locations of any configuration files, and the meaning of any
environment variables or properties that can be set. These descriptions must
also include details of any configuration language used.

=head1 DEPENDENCIES

A list of all of the other modules that this module relies upon, including any
restrictions on versions, and an indication of whether these required modules
are part of the standard Perl distribution, part of the module's distribution,
or must be installed separately.

=head1 INCOMPATIBILITIES

A list of any modules that this module cannot be used in conjunction with.
This may be due to name conflicts in the interface, or competition for system
or program resources, or due to internal limitations of Perl (for example, many
modules that use source code filters are mutually incompatible).

=head1 BUGS AND LIMITATIONS

A list of known problems with the module, together with some indication of
whether they are likely to be fixed in an upcoming release.

Also, a list of restrictions on the features the module does provide: data types
that cannot be handled, performance issues and the circumstances in which they
may arise, practical limitations on the size of data sets, special cases that
are not (yet) handled, etc.

The initial template usually just has:

There are no known bugs in this module.

Please report problems to Ivan Wills (ivan.wills@gmail.com).

Patches are welcome.

=head1 AUTHOR

Ivan Wills - (ivan.wills@gmail.com)

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2010 Ivan Wills (14 Mullion Close, Hornsby Heights, NSW Australia 2077).
All rights reserved.

This module is free software; you can redistribute it and/or modify it under
the same terms as Perl itself. See L<perlartistic>.  This program is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

=cut
