---
name: Game-Life-Adv
version: v0.0.1
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
abstract: |-
  Infrastructure for playing Conway's game of life with
  support for multiple cell types and 2D or 3D boards.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Moose: 0
  Params::Coerce: 0
configure_requires:
  Module::Build: 0.34
provides:
  Game::Life::Adv:
    file: lib/Game/Life/Adv.pm
    version: v0.0.1
  Game::Life::Adv::Board:
    file: lib/Game/Life/Adv/Board.pm
    version: v0.0.1
  Game::Life::Adv::Dim:
    file: lib/Game/Life/Adv/Dim.pm
    version: v0.0.1
  Game::Life::Adv::Life:
    file: lib/Game/Life/Adv/Life.pm
    version: v0.0.1
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
